"""Create database

Revision ID: 70588f6f55d2
Revises: 26bae3ea0439
Create Date: 2022-10-15 21:31:46.116330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70588f6f55d2'
down_revision = '26bae3ea0439'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
