"""update

Revision ID: 9ac08a972b8f
Revises: b05339855c52
Create Date: 2022-10-16 19:43:23.370764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac08a972b8f'
down_revision = 'b05339855c52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Wiki', ['Title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Wiki', type_='unique')
    # ### end Alembic commands ###
