"""Create database

Revision ID: a5c42fc034c0
Revises: 70588f6f55d2
Create Date: 2022-10-15 21:53:38.865434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c42fc034c0'
down_revision = '70588f6f55d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
