"""Create database

Revision ID: b05339855c52
Revises: a5c42fc034c0
Create Date: 2022-10-15 22:44:43.665394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05339855c52'
down_revision = 'a5c42fc034c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
